//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilliantIdea.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentValue
    {
        public int Id { get; set; }
        public int SensorId { get; set; }
        public double Value { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Message { get; set; }
    }
}
