//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilliantIdea.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensors
    {
        public int Id { get; set; }
        public int SensorType { get; set; }
        public string Name { get; set; }
        public double MaxValue { get; set; }
        public double MinValue { get; set; }
        public int ScaleId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
