//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilliantIdea.Persistence.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysCorEntities : DbContext
    {
        public SysCorEntities()
            : base("name=SysCorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public DbSet<Ranges> Ranges { get; set; }
        public DbSet<Scales> Scales { get; set; }
        public DbSet<Sensors> Sensors { get; set; }
        public DbSet<CurrentValue> CurrentValue { get; set; }
        public DbSet<SensedData> SensedData { get; set; }
    }
}
