//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilliantIdea.Persistance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensors
    {
        public Sensors()
        {
            this.CurrentValue = new HashSet<CurrentValue>();
            this.SensedData = new HashSet<SensedData>();
        }
    
        public int Id { get; set; }
        public int SensorType { get; set; }
        public string Name { get; set; }
        public double MaxValue { get; set; }
        public double MinValue { get; set; }
        public int ScaleId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<CurrentValue> CurrentValue { get; set; }
        public virtual ICollection<SensedData> SensedData { get; set; }
    }
}
